print(len('hello'))
print(type(123))
print(type("hello"))
print(type(True))
print(type(1.101))
print(int("123")+ int("456"))
name = input("Enter your name")
length = len(name)
print("Number of letters in your name: " + str(length))